require 'codeclimate-test-reporter'
CodeClimate::TestReporter.start
require 'bundler/setup'
Bundler.require(:default, :development)
require 'soapy_cake'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.expect_with :rspec do |c|
    # Disable the `should` syntax
    c.syntax = :expect
  end
end

ENV['CAKE_API_KEY'] = 'cake-api-key' if ENV['CAKE_API_KEY'].blank?
ENV['CAKE_DOMAIN'] = 'cake-partner-domain.com' if ENV['CAKE_DOMAIN'].blank?

VCR.configure do |c|
  c.cassette_library_dir = 'spec/fixtures/vcr_cassettes'
  c.hook_into :webmock
  c.filter_sensitive_data('cake-api-key') { ENV['CAKE_API_KEY'] }
  c.filter_sensitive_data('cake-partner-domain.com') { ENV['CAKE_DOMAIN'] }
  c.default_cassette_options = { match_requests_on: [:method, :uri, :body] }

  # allow codeclimate-test-reporter to phone home
  c.ignore_hosts 'codeclimate.com'
end
