module SoapyCake
  module Const
    OFFER_STATUS_PUBLIC = 1
    OFFER_STATUS_PRIVATE = 2
    OFFER_STATUS_APPLY_TO_RUN = 3
    OFFER_STATUS_INACTIVE = 4

    OFFER_TYPE_HOSTED = 1
    OFFER_TYPE_HOST_N_POST = 2
    OFFER_TYPE_3RD_PARTY = 3

    CURRENCY_USD = 1
    CURRENCY_EUR = 2
    CURRENCY_GBD = 3
    CURRENCY_AUD = 4
    CURRENCY_CAD = 5

    PRICE_FORMAT_CPA = 1
    PRICE_FORMAT_CPC = 2
    PRICE_FORMAT_CPM = 3
    PRICE_FORMAT_FIXED = 4
    PRICE_FORMAT_REVSHARE = 5

    CONVERSION_BEHAVIOR_SYSTEM = 0
    CONVERSION_BEHAVIOR_ADV_AFF = 1
    CONVERSION_BEHAVIOR_ADV_NO_AFF = 2
    CONVERSION_BEHAVIOR_IGNORE = 3
    CONVERSION_BEHAVIOR_NO_ADV_AFF = 4
    CONVERSION_BEHAVIOR_NO_ADV_NO_AFF = 5
  end
end
